//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    public partial class AWBuildVersion
    {
        #region Primitive Properties
        [DataMember]
        public virtual byte SystemInformationID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Database_Version
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime VersionDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
    }
}
