//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(BusinessEntityAddress))]
    [KnownType(typeof(BusinessEntityContact))]
    [KnownType(typeof(Person))]
    [KnownType(typeof(Store))]
    [KnownType(typeof(Vendor))]
    public partial class BusinessEntity
    {
        #region Primitive Properties
        [DataMember]
        public virtual int BusinessEntityID
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.Guid rowguid
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<BusinessEntityAddress> BusinessEntityAddresses
        {
            get
            {
                if (_businessEntityAddresses == null)
                {
                    var newCollection = new FixupCollection<BusinessEntityAddress>();
                    newCollection.CollectionChanged += FixupBusinessEntityAddresses;
                    _businessEntityAddresses = newCollection;
                }
                return _businessEntityAddresses;
            }
            set
            {
                if (!ReferenceEquals(_businessEntityAddresses, value))
                {
                    var previousValue = _businessEntityAddresses as FixupCollection<BusinessEntityAddress>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBusinessEntityAddresses;
                    }
                    _businessEntityAddresses = value;
                    var newValue = value as FixupCollection<BusinessEntityAddress>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBusinessEntityAddresses;
                    }
                }
            }
        }
        private ICollection<BusinessEntityAddress> _businessEntityAddresses;
        
    
        [DataMember]
        public virtual ICollection<BusinessEntityContact> BusinessEntityContacts
        {
            get
            {
                if (_businessEntityContacts == null)
                {
                    var newCollection = new FixupCollection<BusinessEntityContact>();
                    newCollection.CollectionChanged += FixupBusinessEntityContacts;
                    _businessEntityContacts = newCollection;
                }
                return _businessEntityContacts;
            }
            set
            {
                if (!ReferenceEquals(_businessEntityContacts, value))
                {
                    var previousValue = _businessEntityContacts as FixupCollection<BusinessEntityContact>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBusinessEntityContacts;
                    }
                    _businessEntityContacts = value;
                    var newValue = value as FixupCollection<BusinessEntityContact>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBusinessEntityContacts;
                    }
                }
            }
        }
        private ICollection<BusinessEntityContact> _businessEntityContacts;
        
    
        [DataMember]
        public virtual Person Person
        {
            get { return _person; }
            set
            {
                if (!ReferenceEquals(_person, value))
                {
                    var previousValue = _person;
                    _person = value;
                    FixupPerson(previousValue);
                }
            }
        }
        private Person _person;
        
    
        [DataMember]
        public virtual Store Store
        {
            get { return _store; }
            set
            {
                if (!ReferenceEquals(_store, value))
                {
                    var previousValue = _store;
                    _store = value;
                    FixupStore(previousValue);
                }
            }
        }
        private Store _store;
        
    
        [DataMember]
        public virtual Vendor Vendor
        {
            get { return _vendor; }
            set
            {
                if (!ReferenceEquals(_vendor, value))
                {
                    var previousValue = _vendor;
                    _vendor = value;
                    FixupVendor(previousValue);
                }
            }
        }
        private Vendor _vendor;

        #endregion
        #region Association Fixup
    
        private void FixupPerson(Person previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.BusinessEntity, this))
            {
                previousValue.BusinessEntity = null;
            }
    
            if (Person != null)
            {
                Person.BusinessEntity = this;
            }
        }
    
        private void FixupStore(Store previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.BusinessEntity, this))
            {
                previousValue.BusinessEntity = null;
            }
    
            if (Store != null)
            {
                Store.BusinessEntity = this;
            }
        }
    
        private void FixupVendor(Vendor previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.BusinessEntity, this))
            {
                previousValue.BusinessEntity = null;
            }
    
            if (Vendor != null)
            {
                Vendor.BusinessEntity = this;
            }
        }
    
        private void FixupBusinessEntityAddresses(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (BusinessEntityAddress item in e.NewItems)
                {
                    item.BusinessEntity = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (BusinessEntityAddress item in e.OldItems)
                {
                    if (ReferenceEquals(item.BusinessEntity, this))
                    {
                        item.BusinessEntity = null;
                    }
                }
            }
        }
    
        private void FixupBusinessEntityContacts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (BusinessEntityContact item in e.NewItems)
                {
                    item.BusinessEntity = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (BusinessEntityContact item in e.OldItems)
                {
                    if (ReferenceEquals(item.BusinessEntity, this))
                    {
                        item.BusinessEntity = null;
                    }
                }
            }
        }

        #endregion
    }
}
