//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CountryRegionCurrency))]
    [KnownType(typeof(CurrencyRate))]
    public partial class Currency
    {
        #region Primitive Properties
        [DataMember]
        public virtual string CurrencyCode
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Name
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<CountryRegionCurrency> CountryRegionCurrencies
        {
            get
            {
                if (_countryRegionCurrencies == null)
                {
                    var newCollection = new FixupCollection<CountryRegionCurrency>();
                    newCollection.CollectionChanged += FixupCountryRegionCurrencies;
                    _countryRegionCurrencies = newCollection;
                }
                return _countryRegionCurrencies;
            }
            set
            {
                if (!ReferenceEquals(_countryRegionCurrencies, value))
                {
                    var previousValue = _countryRegionCurrencies as FixupCollection<CountryRegionCurrency>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCountryRegionCurrencies;
                    }
                    _countryRegionCurrencies = value;
                    var newValue = value as FixupCollection<CountryRegionCurrency>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCountryRegionCurrencies;
                    }
                }
            }
        }
        private ICollection<CountryRegionCurrency> _countryRegionCurrencies;
        
    
        [DataMember]
        public virtual ICollection<CurrencyRate> CurrencyRates
        {
            get
            {
                if (_currencyRates == null)
                {
                    var newCollection = new FixupCollection<CurrencyRate>();
                    newCollection.CollectionChanged += FixupCurrencyRates;
                    _currencyRates = newCollection;
                }
                return _currencyRates;
            }
            set
            {
                if (!ReferenceEquals(_currencyRates, value))
                {
                    var previousValue = _currencyRates as FixupCollection<CurrencyRate>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCurrencyRates;
                    }
                    _currencyRates = value;
                    var newValue = value as FixupCollection<CurrencyRate>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCurrencyRates;
                    }
                }
            }
        }
        private ICollection<CurrencyRate> _currencyRates;
        
    
        [DataMember]
        public virtual ICollection<CurrencyRate> CurrencyRates1
        {
            get
            {
                if (_currencyRates1 == null)
                {
                    var newCollection = new FixupCollection<CurrencyRate>();
                    newCollection.CollectionChanged += FixupCurrencyRates1;
                    _currencyRates1 = newCollection;
                }
                return _currencyRates1;
            }
            set
            {
                if (!ReferenceEquals(_currencyRates1, value))
                {
                    var previousValue = _currencyRates1 as FixupCollection<CurrencyRate>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCurrencyRates1;
                    }
                    _currencyRates1 = value;
                    var newValue = value as FixupCollection<CurrencyRate>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCurrencyRates1;
                    }
                }
            }
        }
        private ICollection<CurrencyRate> _currencyRates1;

        #endregion
        #region Association Fixup
    
        private void FixupCountryRegionCurrencies(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CountryRegionCurrency item in e.NewItems)
                {
                    item.Currency = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CountryRegionCurrency item in e.OldItems)
                {
                    if (ReferenceEquals(item.Currency, this))
                    {
                        item.Currency = null;
                    }
                }
            }
        }
    
        private void FixupCurrencyRates(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CurrencyRate item in e.NewItems)
                {
                    item.Currency = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CurrencyRate item in e.OldItems)
                {
                    if (ReferenceEquals(item.Currency, this))
                    {
                        item.Currency = null;
                    }
                }
            }
        }
    
        private void FixupCurrencyRates1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CurrencyRate item in e.NewItems)
                {
                    item.Currency1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CurrencyRate item in e.OldItems)
                {
                    if (ReferenceEquals(item.Currency1, this))
                    {
                        item.Currency1 = null;
                    }
                }
            }
        }

        #endregion
    }
}
