//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    public partial class DatabaseLog
    {
        #region Primitive Properties
        [DataMember]
        public virtual int DatabaseLogID
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime PostTime
        {
            get;
            set;
        }
        [DataMember]
        public virtual string DatabaseUser
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Event
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Schema
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Object
        {
            get;
            set;
        }
        [DataMember]
        public virtual string TSQL
        {
            get;
            set;
        }
        [DataMember]
        public virtual string XmlEvent
        {
            get;
            set;
        }

        #endregion
    }
}
