//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    public partial class ErrorLog
    {
        #region Primitive Properties
        [DataMember]
        public virtual int ErrorLogID
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ErrorTime
        {
            get;
            set;
        }
        [DataMember]
        public virtual string UserName
        {
            get;
            set;
        }
        [DataMember]
        public virtual int ErrorNumber
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> ErrorSeverity
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> ErrorState
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ErrorProcedure
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> ErrorLine
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ErrorMessage
        {
            get;
            set;
        }

        #endregion
    }
}
