//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ProductModelIllustration))]
    public partial class Illustration
    {
        #region Primitive Properties
        [DataMember]
        public virtual int IllustrationID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Diagram
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<ProductModelIllustration> ProductModelIllustrations
        {
            get
            {
                if (_productModelIllustrations == null)
                {
                    var newCollection = new FixupCollection<ProductModelIllustration>();
                    newCollection.CollectionChanged += FixupProductModelIllustrations;
                    _productModelIllustrations = newCollection;
                }
                return _productModelIllustrations;
            }
            set
            {
                if (!ReferenceEquals(_productModelIllustrations, value))
                {
                    var previousValue = _productModelIllustrations as FixupCollection<ProductModelIllustration>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProductModelIllustrations;
                    }
                    _productModelIllustrations = value;
                    var newValue = value as FixupCollection<ProductModelIllustration>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProductModelIllustrations;
                    }
                }
            }
        }
        private ICollection<ProductModelIllustration> _productModelIllustrations;

        #endregion
        #region Association Fixup
    
        private void FixupProductModelIllustrations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProductModelIllustration item in e.NewItems)
                {
                    item.Illustration = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductModelIllustration item in e.OldItems)
                {
                    if (ReferenceEquals(item.Illustration, this))
                    {
                        item.Illustration = null;
                    }
                }
            }
        }

        #endregion
    }
}
