//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Person))]
    [KnownType(typeof(CreditCard))]
    public partial class PersonCreditCard
    {
        #region Primitive Properties
        [DataMember]
        public virtual int BusinessEntityID
        {
            get { return _businessEntityID; }
            set
            {
                if (_businessEntityID != value)
                {
                    if (Person != null && Person.BusinessEntityID != value)
                    {
                        Person = null;
                    }
                    _businessEntityID = value;
                }
            }
        }
        private int _businessEntityID;
        [DataMember]
        public virtual int CreditCardID
        {
            get { return _creditCardID; }
            set
            {
                if (_creditCardID != value)
                {
                    if (CreditCard != null && CreditCard.CreditCardID != value)
                    {
                        CreditCard = null;
                    }
                    _creditCardID = value;
                }
            }
        }
        private int _creditCardID;
        [DataMember]
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual Person Person
        {
            get { return _person; }
            set
            {
                if (!ReferenceEquals(_person, value))
                {
                    var previousValue = _person;
                    _person = value;
                    FixupPerson(previousValue);
                }
            }
        }
        private Person _person;
        
    
        [DataMember]
        public virtual CreditCard CreditCard
        {
            get { return _creditCard; }
            set
            {
                if (!ReferenceEquals(_creditCard, value))
                {
                    var previousValue = _creditCard;
                    _creditCard = value;
                    FixupCreditCard(previousValue);
                }
            }
        }
        private CreditCard _creditCard;

        #endregion
        #region Association Fixup
    
        private void FixupPerson(Person previousValue)
        {
            if (previousValue != null && previousValue.PersonCreditCards.Contains(this))
            {
                previousValue.PersonCreditCards.Remove(this);
            }
    
            if (Person != null)
            {
                if (!Person.PersonCreditCards.Contains(this))
                {
                    Person.PersonCreditCards.Add(this);
                }
                if (BusinessEntityID != Person.BusinessEntityID)
                {
                    BusinessEntityID = Person.BusinessEntityID;
                }
            }
        }
    
        private void FixupCreditCard(CreditCard previousValue)
        {
            if (previousValue != null && previousValue.PersonCreditCards.Contains(this))
            {
                previousValue.PersonCreditCards.Remove(this);
            }
    
            if (CreditCard != null)
            {
                if (!CreditCard.PersonCreditCards.Contains(this))
                {
                    CreditCard.PersonCreditCards.Add(this);
                }
                if (CreditCardID != CreditCard.CreditCardID)
                {
                    CreditCardID = CreditCard.CreditCardID;
                }
            }
        }

        #endregion
    }
}
