//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ProductSubcategory))]
    public partial class ProductCategory
    {
        #region Primitive Properties
        [DataMember]
        public virtual int ProductCategoryID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Name
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.Guid rowguid
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<ProductSubcategory> ProductSubcategories
        {
            get
            {
                if (_productSubcategories == null)
                {
                    var newCollection = new FixupCollection<ProductSubcategory>();
                    newCollection.CollectionChanged += FixupProductSubcategories;
                    _productSubcategories = newCollection;
                }
                return _productSubcategories;
            }
            set
            {
                if (!ReferenceEquals(_productSubcategories, value))
                {
                    var previousValue = _productSubcategories as FixupCollection<ProductSubcategory>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProductSubcategories;
                    }
                    _productSubcategories = value;
                    var newValue = value as FixupCollection<ProductSubcategory>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProductSubcategories;
                    }
                }
            }
        }
        private ICollection<ProductSubcategory> _productSubcategories;

        #endregion
        #region Association Fixup
    
        private void FixupProductSubcategories(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProductSubcategory item in e.NewItems)
                {
                    item.ProductCategory = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductSubcategory item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductCategory, this))
                    {
                        item.ProductCategory = null;
                    }
                }
            }
        }

        #endregion
    }
}
