//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Product))]
    [KnownType(typeof(ProductCategory))]
    public partial class ProductSubcategory
    {
        #region Primitive Properties
        [DataMember]
        public virtual int ProductSubcategoryID
        {
            get;
            set;
        }
        [DataMember]
        public virtual int ProductCategoryID
        {
            get { return _productCategoryID; }
            set
            {
                if (_productCategoryID != value)
                {
                    if (ProductCategory != null && ProductCategory.ProductCategoryID != value)
                    {
                        ProductCategory = null;
                    }
                    _productCategoryID = value;
                }
            }
        }
        private int _productCategoryID;
        [DataMember]
        public virtual string Name
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.Guid rowguid
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<Product> Products
        {
            get
            {
                if (_products == null)
                {
                    var newCollection = new FixupCollection<Product>();
                    newCollection.CollectionChanged += FixupProducts;
                    _products = newCollection;
                }
                return _products;
            }
            set
            {
                if (!ReferenceEquals(_products, value))
                {
                    var previousValue = _products as FixupCollection<Product>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProducts;
                    }
                    _products = value;
                    var newValue = value as FixupCollection<Product>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProducts;
                    }
                }
            }
        }
        private ICollection<Product> _products;
        
    
        [DataMember]
        public virtual ProductCategory ProductCategory
        {
            get { return _productCategory; }
            set
            {
                if (!ReferenceEquals(_productCategory, value))
                {
                    var previousValue = _productCategory;
                    _productCategory = value;
                    FixupProductCategory(previousValue);
                }
            }
        }
        private ProductCategory _productCategory;

        #endregion
        #region Association Fixup
    
        private void FixupProductCategory(ProductCategory previousValue)
        {
            if (previousValue != null && previousValue.ProductSubcategories.Contains(this))
            {
                previousValue.ProductSubcategories.Remove(this);
            }
    
            if (ProductCategory != null)
            {
                if (!ProductCategory.ProductSubcategories.Contains(this))
                {
                    ProductCategory.ProductSubcategories.Add(this);
                }
                if (ProductCategoryID != ProductCategory.ProductCategoryID)
                {
                    ProductCategoryID = ProductCategory.ProductCategoryID;
                }
            }
        }
    
        private void FixupProducts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Product item in e.NewItems)
                {
                    item.ProductSubcategory = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Product item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductSubcategory, this))
                    {
                        item.ProductSubcategory = null;
                    }
                }
            }
        }

        #endregion
    }
}
