//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Product))]
    [KnownType(typeof(ProductPhoto))]
    public partial class ProductProductPhoto
    {
        #region Primitive Properties
        [DataMember]
        public virtual int ProductID
        {
            get { return _productID; }
            set
            {
                if (_productID != value)
                {
                    if (Product != null && Product.ProductID != value)
                    {
                        Product = null;
                    }
                    _productID = value;
                }
            }
        }
        private int _productID;
        [DataMember]
        public virtual int ProductPhotoID
        {
            get { return _productPhotoID; }
            set
            {
                if (_productPhotoID != value)
                {
                    if (ProductPhoto != null && ProductPhoto.ProductPhotoID != value)
                    {
                        ProductPhoto = null;
                    }
                    _productPhotoID = value;
                }
            }
        }
        private int _productPhotoID;
        [DataMember]
        public virtual bool Primary
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual Product Product
        {
            get { return _product; }
            set
            {
                if (!ReferenceEquals(_product, value))
                {
                    var previousValue = _product;
                    _product = value;
                    FixupProduct(previousValue);
                }
            }
        }
        private Product _product;
        
    
        [DataMember]
        public virtual ProductPhoto ProductPhoto
        {
            get { return _productPhoto; }
            set
            {
                if (!ReferenceEquals(_productPhoto, value))
                {
                    var previousValue = _productPhoto;
                    _productPhoto = value;
                    FixupProductPhoto(previousValue);
                }
            }
        }
        private ProductPhoto _productPhoto;

        #endregion
        #region Association Fixup
    
        private void FixupProduct(Product previousValue)
        {
            if (previousValue != null && previousValue.ProductProductPhotoes.Contains(this))
            {
                previousValue.ProductProductPhotoes.Remove(this);
            }
    
            if (Product != null)
            {
                if (!Product.ProductProductPhotoes.Contains(this))
                {
                    Product.ProductProductPhotoes.Add(this);
                }
                if (ProductID != Product.ProductID)
                {
                    ProductID = Product.ProductID;
                }
            }
        }
    
        private void FixupProductPhoto(ProductPhoto previousValue)
        {
            if (previousValue != null && previousValue.ProductProductPhotoes.Contains(this))
            {
                previousValue.ProductProductPhotoes.Remove(this);
            }
    
            if (ProductPhoto != null)
            {
                if (!ProductPhoto.ProductProductPhotoes.Contains(this))
                {
                    ProductPhoto.ProductProductPhotoes.Add(this);
                }
                if (ProductPhotoID != ProductPhoto.ProductPhotoID)
                {
                    ProductPhotoID = ProductPhoto.ProductPhotoID;
                }
            }
        }

        #endregion
    }
}
