//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Address))]
    [KnownType(typeof(ShipMethod))]
    [KnownType(typeof(CreditCard))]
    [KnownType(typeof(CurrencyRate))]
    [KnownType(typeof(Customer))]
    [KnownType(typeof(SalesOrderDetail))]
    [KnownType(typeof(SalesPerson))]
    [KnownType(typeof(SalesTerritory))]
    [KnownType(typeof(SalesOrderHeaderSalesReason))]
    public partial class SalesOrderHeader
    {
        #region Primitive Properties
        [DataMember]
        public virtual int SalesOrderID
        {
            get;
            set;
        }
        [DataMember]
        public virtual byte RevisionNumber
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime OrderDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime DueDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> ShipDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual byte Status
        {
            get;
            set;
        }
        [DataMember]
        public virtual bool OnlineOrderFlag
        {
            get;
            set;
        }
        [DataMember]
        public virtual string SalesOrderNumber
        {
            get;
            set;
        }
        [DataMember]
        public virtual string PurchaseOrderNumber
        {
            get;
            set;
        }
        [DataMember]
        public virtual string AccountNumber
        {
            get;
            set;
        }
        [DataMember]
        public virtual int CustomerID
        {
            get { return _customerID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_customerID != value)
                    {
                        if (Customer != null && Customer.CustomerID != value)
                        {
                            Customer = null;
                        }
                        _customerID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _customerID;
        [DataMember]
        public virtual Nullable<int> SalesPersonID
        {
            get { return _salesPersonID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_salesPersonID != value)
                    {
                        if (SalesPerson != null && SalesPerson.BusinessEntityID != value)
                        {
                            SalesPerson = null;
                        }
                        _salesPersonID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _salesPersonID;
        [DataMember]
        public virtual Nullable<int> TerritoryID
        {
            get { return _territoryID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_territoryID != value)
                    {
                        if (SalesTerritory != null && SalesTerritory.TerritoryID != value)
                        {
                            SalesTerritory = null;
                        }
                        _territoryID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _territoryID;
        [DataMember]
        public virtual int BillToAddressID
        {
            get { return _billToAddressID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_billToAddressID != value)
                    {
                        if (Address != null && Address.AddressID != value)
                        {
                            Address = null;
                        }
                        _billToAddressID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _billToAddressID;
        [DataMember]
        public virtual int ShipToAddressID
        {
            get { return _shipToAddressID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_shipToAddressID != value)
                    {
                        if (Address1 != null && Address1.AddressID != value)
                        {
                            Address1 = null;
                        }
                        _shipToAddressID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _shipToAddressID;
        [DataMember]
        public virtual int ShipMethodID
        {
            get { return _shipMethodID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_shipMethodID != value)
                    {
                        if (ShipMethod != null && ShipMethod.ShipMethodID != value)
                        {
                            ShipMethod = null;
                        }
                        _shipMethodID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _shipMethodID;
        [DataMember]
        public virtual Nullable<int> CreditCardID
        {
            get { return _creditCardID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_creditCardID != value)
                    {
                        if (CreditCard != null && CreditCard.CreditCardID != value)
                        {
                            CreditCard = null;
                        }
                        _creditCardID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _creditCardID;
        [DataMember]
        public virtual string CreditCardApprovalCode
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> CurrencyRateID
        {
            get { return _currencyRateID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_currencyRateID != value)
                    {
                        if (CurrencyRate != null && CurrencyRate.CurrencyRateID != value)
                        {
                            CurrencyRate = null;
                        }
                        _currencyRateID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _currencyRateID;
        [DataMember]
        public virtual decimal SubTotal
        {
            get;
            set;
        }
        [DataMember]
        public virtual decimal TaxAmt
        {
            get;
            set;
        }
        [DataMember]
        public virtual decimal Freight
        {
            get;
            set;
        }
        [DataMember]
        public virtual decimal TotalDue
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Comment
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.Guid rowguid
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual Address Address
        {
            get { return _address; }
            set
            {
                if (!ReferenceEquals(_address, value))
                {
                    var previousValue = _address;
                    _address = value;
                    FixupAddress(previousValue);
                }
            }
        }
        private Address _address;
        
    
        [DataMember]
        public virtual Address Address1
        {
            get { return _address1; }
            set
            {
                if (!ReferenceEquals(_address1, value))
                {
                    var previousValue = _address1;
                    _address1 = value;
                    FixupAddress1(previousValue);
                }
            }
        }
        private Address _address1;
        
    
        [DataMember]
        public virtual ShipMethod ShipMethod
        {
            get { return _shipMethod; }
            set
            {
                if (!ReferenceEquals(_shipMethod, value))
                {
                    var previousValue = _shipMethod;
                    _shipMethod = value;
                    FixupShipMethod(previousValue);
                }
            }
        }
        private ShipMethod _shipMethod;
        
    
        [DataMember]
        public virtual CreditCard CreditCard
        {
            get { return _creditCard; }
            set
            {
                if (!ReferenceEquals(_creditCard, value))
                {
                    var previousValue = _creditCard;
                    _creditCard = value;
                    FixupCreditCard(previousValue);
                }
            }
        }
        private CreditCard _creditCard;
        
    
        [DataMember]
        public virtual CurrencyRate CurrencyRate
        {
            get { return _currencyRate; }
            set
            {
                if (!ReferenceEquals(_currencyRate, value))
                {
                    var previousValue = _currencyRate;
                    _currencyRate = value;
                    FixupCurrencyRate(previousValue);
                }
            }
        }
        private CurrencyRate _currencyRate;
        
    
        [DataMember]
        public virtual Customer Customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    FixupCustomer(previousValue);
                }
            }
        }
        private Customer _customer;
        
    
        [DataMember]
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails
        {
            get
            {
                if (_salesOrderDetails == null)
                {
                    var newCollection = new FixupCollection<SalesOrderDetail>();
                    newCollection.CollectionChanged += FixupSalesOrderDetails;
                    _salesOrderDetails = newCollection;
                }
                return _salesOrderDetails;
            }
            set
            {
                if (!ReferenceEquals(_salesOrderDetails, value))
                {
                    var previousValue = _salesOrderDetails as FixupCollection<SalesOrderDetail>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSalesOrderDetails;
                    }
                    _salesOrderDetails = value;
                    var newValue = value as FixupCollection<SalesOrderDetail>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSalesOrderDetails;
                    }
                }
            }
        }
        private ICollection<SalesOrderDetail> _salesOrderDetails;
        
    
        [DataMember]
        public virtual SalesPerson SalesPerson
        {
            get { return _salesPerson; }
            set
            {
                if (!ReferenceEquals(_salesPerson, value))
                {
                    var previousValue = _salesPerson;
                    _salesPerson = value;
                    FixupSalesPerson(previousValue);
                }
            }
        }
        private SalesPerson _salesPerson;
        
    
        [DataMember]
        public virtual SalesTerritory SalesTerritory
        {
            get { return _salesTerritory; }
            set
            {
                if (!ReferenceEquals(_salesTerritory, value))
                {
                    var previousValue = _salesTerritory;
                    _salesTerritory = value;
                    FixupSalesTerritory(previousValue);
                }
            }
        }
        private SalesTerritory _salesTerritory;
        
    
        [DataMember]
        public virtual ICollection<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons
        {
            get
            {
                if (_salesOrderHeaderSalesReasons == null)
                {
                    var newCollection = new FixupCollection<SalesOrderHeaderSalesReason>();
                    newCollection.CollectionChanged += FixupSalesOrderHeaderSalesReasons;
                    _salesOrderHeaderSalesReasons = newCollection;
                }
                return _salesOrderHeaderSalesReasons;
            }
            set
            {
                if (!ReferenceEquals(_salesOrderHeaderSalesReasons, value))
                {
                    var previousValue = _salesOrderHeaderSalesReasons as FixupCollection<SalesOrderHeaderSalesReason>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSalesOrderHeaderSalesReasons;
                    }
                    _salesOrderHeaderSalesReasons = value;
                    var newValue = value as FixupCollection<SalesOrderHeaderSalesReason>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSalesOrderHeaderSalesReasons;
                    }
                }
            }
        }
        private ICollection<SalesOrderHeaderSalesReason> _salesOrderHeaderSalesReasons;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupAddress(Address previousValue)
        {
            if (previousValue != null && previousValue.SalesOrderHeaders.Contains(this))
            {
                previousValue.SalesOrderHeaders.Remove(this);
            }
    
            if (Address != null)
            {
                if (!Address.SalesOrderHeaders.Contains(this))
                {
                    Address.SalesOrderHeaders.Add(this);
                }
                if (BillToAddressID != Address.AddressID)
                {
                    BillToAddressID = Address.AddressID;
                }
            }
        }
    
        private void FixupAddress1(Address previousValue)
        {
            if (previousValue != null && previousValue.SalesOrderHeaders1.Contains(this))
            {
                previousValue.SalesOrderHeaders1.Remove(this);
            }
    
            if (Address1 != null)
            {
                if (!Address1.SalesOrderHeaders1.Contains(this))
                {
                    Address1.SalesOrderHeaders1.Add(this);
                }
                if (ShipToAddressID != Address1.AddressID)
                {
                    ShipToAddressID = Address1.AddressID;
                }
            }
        }
    
        private void FixupShipMethod(ShipMethod previousValue)
        {
            if (previousValue != null && previousValue.SalesOrderHeaders.Contains(this))
            {
                previousValue.SalesOrderHeaders.Remove(this);
            }
    
            if (ShipMethod != null)
            {
                if (!ShipMethod.SalesOrderHeaders.Contains(this))
                {
                    ShipMethod.SalesOrderHeaders.Add(this);
                }
                if (ShipMethodID != ShipMethod.ShipMethodID)
                {
                    ShipMethodID = ShipMethod.ShipMethodID;
                }
            }
        }
    
        private void FixupCreditCard(CreditCard previousValue)
        {
            if (previousValue != null && previousValue.SalesOrderHeaders.Contains(this))
            {
                previousValue.SalesOrderHeaders.Remove(this);
            }
    
            if (CreditCard != null)
            {
                if (!CreditCard.SalesOrderHeaders.Contains(this))
                {
                    CreditCard.SalesOrderHeaders.Add(this);
                }
                if (CreditCardID != CreditCard.CreditCardID)
                {
                    CreditCardID = CreditCard.CreditCardID;
                }
            }
            else if (!_settingFK)
            {
                CreditCardID = null;
            }
        }
    
        private void FixupCurrencyRate(CurrencyRate previousValue)
        {
            if (previousValue != null && previousValue.SalesOrderHeaders.Contains(this))
            {
                previousValue.SalesOrderHeaders.Remove(this);
            }
    
            if (CurrencyRate != null)
            {
                if (!CurrencyRate.SalesOrderHeaders.Contains(this))
                {
                    CurrencyRate.SalesOrderHeaders.Add(this);
                }
                if (CurrencyRateID != CurrencyRate.CurrencyRateID)
                {
                    CurrencyRateID = CurrencyRate.CurrencyRateID;
                }
            }
            else if (!_settingFK)
            {
                CurrencyRateID = null;
            }
        }
    
        private void FixupCustomer(Customer previousValue)
        {
            if (previousValue != null && previousValue.SalesOrderHeaders.Contains(this))
            {
                previousValue.SalesOrderHeaders.Remove(this);
            }
    
            if (Customer != null)
            {
                if (!Customer.SalesOrderHeaders.Contains(this))
                {
                    Customer.SalesOrderHeaders.Add(this);
                }
                if (CustomerID != Customer.CustomerID)
                {
                    CustomerID = Customer.CustomerID;
                }
            }
        }
    
        private void FixupSalesPerson(SalesPerson previousValue)
        {
            if (previousValue != null && previousValue.SalesOrderHeaders.Contains(this))
            {
                previousValue.SalesOrderHeaders.Remove(this);
            }
    
            if (SalesPerson != null)
            {
                if (!SalesPerson.SalesOrderHeaders.Contains(this))
                {
                    SalesPerson.SalesOrderHeaders.Add(this);
                }
                if (SalesPersonID != SalesPerson.BusinessEntityID)
                {
                    SalesPersonID = SalesPerson.BusinessEntityID;
                }
            }
            else if (!_settingFK)
            {
                SalesPersonID = null;
            }
        }
    
        private void FixupSalesTerritory(SalesTerritory previousValue)
        {
            if (previousValue != null && previousValue.SalesOrderHeaders.Contains(this))
            {
                previousValue.SalesOrderHeaders.Remove(this);
            }
    
            if (SalesTerritory != null)
            {
                if (!SalesTerritory.SalesOrderHeaders.Contains(this))
                {
                    SalesTerritory.SalesOrderHeaders.Add(this);
                }
                if (TerritoryID != SalesTerritory.TerritoryID)
                {
                    TerritoryID = SalesTerritory.TerritoryID;
                }
            }
            else if (!_settingFK)
            {
                TerritoryID = null;
            }
        }
    
        private void FixupSalesOrderDetails(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SalesOrderDetail item in e.NewItems)
                {
                    item.SalesOrderHeader = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SalesOrderDetail item in e.OldItems)
                {
                    if (ReferenceEquals(item.SalesOrderHeader, this))
                    {
                        item.SalesOrderHeader = null;
                    }
                }
            }
        }
    
        private void FixupSalesOrderHeaderSalesReasons(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SalesOrderHeaderSalesReason item in e.NewItems)
                {
                    item.SalesOrderHeader = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SalesOrderHeaderSalesReason item in e.OldItems)
                {
                    if (ReferenceEquals(item.SalesOrderHeader, this))
                    {
                        item.SalesOrderHeader = null;
                    }
                }
            }
        }

        #endregion
    }
}
