//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(SalesOrderHeaderSalesReason))]
    public partial class SalesReason
    {
        #region Primitive Properties
        [DataMember]
        public virtual int SalesReasonID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Name
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ReasonType
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons
        {
            get
            {
                if (_salesOrderHeaderSalesReasons == null)
                {
                    var newCollection = new FixupCollection<SalesOrderHeaderSalesReason>();
                    newCollection.CollectionChanged += FixupSalesOrderHeaderSalesReasons;
                    _salesOrderHeaderSalesReasons = newCollection;
                }
                return _salesOrderHeaderSalesReasons;
            }
            set
            {
                if (!ReferenceEquals(_salesOrderHeaderSalesReasons, value))
                {
                    var previousValue = _salesOrderHeaderSalesReasons as FixupCollection<SalesOrderHeaderSalesReason>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSalesOrderHeaderSalesReasons;
                    }
                    _salesOrderHeaderSalesReasons = value;
                    var newValue = value as FixupCollection<SalesOrderHeaderSalesReason>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSalesOrderHeaderSalesReasons;
                    }
                }
            }
        }
        private ICollection<SalesOrderHeaderSalesReason> _salesOrderHeaderSalesReasons;

        #endregion
        #region Association Fixup
    
        private void FixupSalesOrderHeaderSalesReasons(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SalesOrderHeaderSalesReason item in e.NewItems)
                {
                    item.SalesReason = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SalesOrderHeaderSalesReason item in e.OldItems)
                {
                    if (ReferenceEquals(item.SalesReason, this))
                    {
                        item.SalesReason = null;
                    }
                }
            }
        }

        #endregion
    }
}
