//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTO_Mapping_Test_Entities
{
    [DataContract(IsReference = true)]
    public partial class TransactionHistoryArchive
    {
        #region Primitive Properties
        [DataMember]
        public virtual int TransactionID
        {
            get;
            set;
        }
        [DataMember]
        public virtual int ProductID
        {
            get;
            set;
        }
        [DataMember]
        public virtual int ReferenceOrderID
        {
            get;
            set;
        }
        [DataMember]
        public virtual int ReferenceOrderLineID
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime TransactionDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual string TransactionType
        {
            get;
            set;
        }
        [DataMember]
        public virtual int Quantity
        {
            get;
            set;
        }
        [DataMember]
        public virtual decimal ActualCost
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
    }
}
